
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Jun 27 23:30:02 BRT 2019
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OP = 12;
  public static final int INT = 11;
  public static final int WHILE = 9;
  public static final int APAR = 4;
  public static final int THEN = 7;
  public static final int EQUAL = 2;
  public static final int EOF = 0;
  public static final int IF = 6;
  public static final int ID = 13;
  public static final int ELSE = 8;
  public static final int error = 1;
  public static final int ESCREVA = 3;
  public static final int DO = 10;
  public static final int FPAR = 5;
}

